# ---
# id: dependabot/dependabot
# category: dependabot
# type: template
# name: Dependabot Configuration
# description: Go modules Dependabot config
# targetPath: .github/dependabot.yml
# secrets: []
# inputs: []
# triggers: []
# variants:
#   - name: go
#     description: Go modules config
# ---

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "go"
